@baseUrl = http://localhost:3003
@basePath = api/users

GET {{baseUrl}}/{{basePath}}

###

POST {{baseUrl}}/{{basePath}}
Content-Type: application/json

{
    "username": "kekalainen",
    "password": "hunter2",
    "name": "Kekalainen"
}
